### ISSUE TITLE
Calling `FAIL_* macros should be allowed from outside the `SVTESTS block

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#5] opened 2016-06-07 20:27 UTC
Being able to call `FAIL_\* macros from inside user defined methods would make it easier for users to encapsulate code for checks that are needed in multiple tests.

It should also be possible to use calls to `FAIL_\* inside mocks.

**Comment by nosnhojn** [comment] 2016-06-08 12:49
turns out your new code has exposed bugs in my test suite! that's good... kind of ;)

I'll fix those up and release your new feature asap. thx for getting to this. browsed the solution and it looks solid.

-neil

**Comment by tudortimi** [comment] 2016-06-08 18:01
It wasn't much of a change :)

**Comment by nosnhojn** [comment] 2016-06-09 03:09
so I merged this but was wondering what you intended in the new test you added. as it stands, it's a failing test. I prefer passing examples so the output is positive for users. Also so the examples pass in the regression. Can you change that? or if you intend a failure, maybe move it to it's own test directory and out of the examples.

**Comment by tudortimi** [comment] 2016-06-09 05:50
It was supposed to contain bugs that the unit tests found. It was more of a
trial. I'll can make it pass.

**Closed as completed** 2020-08-16 17:02 UTC
